version: '3.7'

x-anchors:
  environment: &env
    NODE_ENV: ${NODE_ENV:-development}
  env_file: &env-files
      - ./.env

services:
  nginx:
    image: nginx:1.18-alpine
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./nginx/conf.d:/etc/nginx/conf.d:ro
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     - ./certbot/conf:/etc/letsencrypt
    networks:
      - backend
    depends_on:
      - ui

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  ui:
    build:
      context: ./ui
      dockerfile: dev.Dockerfile
    volumes:
      - ./ui:/usr/src/app
    networks:
        - backend
    env_file: *env-files
    environment: *env

  ws:
    build:
      context: ./ws
      dockerfile: Dockerfile
    volumes:
      - ./ws/src:/var/www/html
    networks:
      - backend

  coturn:
    build:
      context: ./docker/coturn
      dockerfile: Dockerfile
    ports:
      - "3478:3478"
      - "3479:3479"
      - "5349:5349"
      - "5350:5350"
    volumes:
      - ./docker/coturn/turnserver-alt.conf:/etc/turnserver.conf
      - ./certbot/conf:/etc/letsencrypt

networks:
  backend:
    driver: bridge

volumes:
  share: {}